/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tipcalculator;

/**
 *
 * @author Shwetha
 */
public class Configuration extends javax.swing.JFrame {

    /**
     * Creates new form Configuration
     */
    public static int Max = 20;
    public static int Min = 0;
    public static boolean selected_deduction = false;
    public static boolean selected_tax = false;
    
    
    public Configuration() {
        initComponents();
        Minimum.setColumns(4);
        Maximum.setColumns(4);
        
        if(selected_deduction == true)
        {
            Deduction_Include.setSelected(true);
        }
        
        if(selected_tax == true)
        {
            Tax_Include.setSelected(true);
        }
        
        Maximum.setText(Integer.toString(Max));
        Minimum.setText(Integer.toString(Min));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Minimum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Maximum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tax_Include = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        Deduction_Include = new javax.swing.JCheckBox();
        Configure = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Minimum Tip Rate");

        Minimum.setText("0");
        Minimum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimumActionPerformed(evt);
            }
        });

        jLabel2.setText("Maximum Tip Rate");

        Maximum.setText("20");
        Maximum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximumActionPerformed(evt);
            }
        });

        jLabel3.setText("Include Tax");

        Tax_Include.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tax_IncludeActionPerformed(evt);
            }
        });

        jLabel4.setText("Include Deduction");

        Deduction_Include.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deduction_IncludeActionPerformed(evt);
            }
        });

        Configure.setText("OK");
        Configure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Maximum, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(Minimum)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Deduction_Include))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(40, 40, 40)
                            .addComponent(Tax_Include))))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Configure)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Minimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Maximum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tax_Include))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deduction_Include))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Configure)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimumActionPerformed

    private void Deduction_IncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deduction_IncludeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Deduction_IncludeActionPerformed

    private void MaximumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MaximumActionPerformed

    private void Tax_IncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tax_IncludeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Tax_IncludeActionPerformed

    private void ConfigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigureActionPerformed
        // TODO add your handling code here:
       
        Min = Integer.parseInt(Minimum.getText());
        Max = Integer.parseInt(Maximum.getText());
        
        
        TipFrame f1 = new TipFrame();
       
 
       f1.jTextField1.setText(Integer.toString(f1.guests));
       f1.jTextField2.setText(Double.toString(f1.billtotal));
       
       if(f1.jTextField3.isEnabled() == true)
       {
            f1.jTextField3.setText(Double.toString(f1.deduction));
            f1.enabled_deduction = true;
       }
       else
       {
           f1.jTextField3.setText("");
       }
       
       if(f1.jTextField4.isEnabled() == true)
       {
            f1.jTextField4.setText(Double.toString(f1.tax));
            f1.enabled_tax = true;
       }
       else
       {
           f1.jTextField4.setText("");
       }
      
        f1.tipRate = (Max-Min)*f1.q/100;
        f1.jTextField5.setText(Double.toString(f1.tipRate));
        
        
        f1.flag_Tailor = true;
        
        if(Tax_Include.isSelected() == true)
        {
            f1.jTextField4.setEnabled(true);
            selected_tax = true;
        }
        
        if(Deduction_Include.isSelected() == true)
        {
            f1.jTextField3.setEnabled(true);
            selected_deduction = true;
        }
        
        
        String s1 = Minimum.getText();
        int min = Integer.parseInt(s1);
        
        String s2 = Maximum.getText();
        int max = Integer.parseInt(s2);
        
        if(min<0)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Minimum Entry!");
            Minimum.setText("0");
            this.setVisible(true);
            f1.setVisible(false);
        }
        
        else if(max>20)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Maximum entry!");
            Maximum.setText("20");
            this.setVisible(true);
            f1.setVisible(false);
        }
        
        else if(min>=0 && max<=20)
        {
            if(min>max)
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Min > Max!");
            }
            this.setVisible(false);
            f1.setVisible(true);
        }
        
        else
        {
            this.setVisible(false);
            f1.setVisible(true);
        }
    }//GEN-LAST:event_ConfigureActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Configure;
    public javax.swing.JCheckBox Deduction_Include;
    public javax.swing.JTextField Maximum;
    public javax.swing.JTextField Minimum;
    public javax.swing.JCheckBox Tax_Include;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
